// <auto-generated />
using BackendData.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("BackendData.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralsightUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TwitterAlias")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steve Smith",
                            PluralsightUrl = "https://www.pluralsight.com/authors/steve-smith",
                            TwitterAlias = "ardalis"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Julie Lerman",
                            PluralsightUrl = "https://www.pluralsight.com/authors/julie-lerman",
                            TwitterAlias = "julialerman"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
